edge_dataframe:
  cols_to_encode:
    - Date
    - Hom
    - Opp

train_autoencoder:
  epochs: 5

infer_with_autoencoder:
  cols_to_encode:
    - Date

graph_nx:
  edge_tuple_src: Opp
  edge_tuple_dst: Hom
  n_targets: []
  e_targets: [Opp.1, Tm]
